# Site settings
name: Pooja Adhikari
title: Pooja Adhikari | Back End Software Engineer
description: Software engineer designing thoughtful backend systems that quietly power beautiful user experiences.
url: https://pooja-adhikari19.github.io/
baseurl: ''
email: p.adhikari1911@gmail.com
cover: https://pooja-adhikari19.github.io/img/og.png
logo: https://pooja-adhikari19.github.io/img/emojis/technologist.png
resume: https://pooja-adhikari19.github.io/resume.pdf
social:
  - title: email
    url: mailto:p.adhikari1911@gmail.com
  - title: twitter
    url: https://twitter.com/pooja1911
  - title: github
    url: https://github.com/pooja-adhikari19
  - title: linkedin
    url: https://www.linkedin.com/in/pooja1911

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
